administration/urls.py
from django.urls import path

from . views import *

urlpatterns = [
    path("", admin_view_redirect, name="redirect"),
    path("dashboard/", admin_view, name="adminview"),
    path("users/", users, name="users"),
    # path("profile/", profile, name="profile"),
    # path("settings/", settings, name="settings"),
    # path("database/", database_view, name="database"),
]

authentication/urls.py
from django.urls import path

from . views import *

app_name = 'authentication'

urlpatterns = [
    path("", authentication, name="authentication"),
    path("logout", logout_view, name="logout")
]

base/urls.py
from django.urls import path

from . views import *

urlpatterns = [
    path("", home, name="home")
]

dhvsuarchives/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path("home/", include("base.urls")),
    path("library/", include("library.urls")),
    path("administrator/", include("administration.urls")),
]

library/urls.py
from django.urls import path

from . views import *

urlpatterns = [
    path("", library, name="library"),
    path("documents/", documents, name="documents"),
    path("document/<int:id>", document, name="document"),
]

administration/models.py
from django.db import models

# Create your models here.

library/models.py
from django.db import models

class Department(models.Model):
    department = models.CharField(max_length=64)
    abbreviation = models.CharField(max_length=16)

    def __str__(self) -> str:
        return self.abbreviation

class Group(models.Model):
    uid = models.CharField(max_length=6)

    def __str__(self) -> str:
        return self.uid

class Course(models.Model):
    course = models.CharField(max_length=64)
    abbreviation = models.CharField(max_length=16)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, default=-1)

    def __str__(self) -> str:
        return self.abbreviation

class Document(models.Model):
    title = models.CharField(max_length=128)
    school_year = models.CharField(max_length=9)
    abstract = models.TextField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=-1)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, default=-1)
    file = models.FileField(upload_to='documents/')

    approved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=64)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, default=-1)

    def __str__(self) -> str:
        return self.name

class Adviser(models.Model):
    name = models.CharField(max_length=64)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, default=-1)

    def __str__(self) -> str:
        return self.name

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    error_messages = {
        'password_mismatch': (""),
        'password_too_short': (""),
        'password_common': (""),
        'username': {
            'required': (""),
            'unique': (""),
            'invalid': (""),
        },
        'email': {
            'required': (""),
            'unique': (""),
            'invalid': (""),
        },
    }

    username = forms.CharField(label="", error_messages=error_messages, widget=forms.TextInput(attrs={"placeholder": "Username"}))
    email = forms.EmailField(label="", error_messages=error_messages, required=True, widget=forms.EmailInput(attrs={"placeholder": "myemail@dhvsu.edu.ph"}))
    password1 = forms.CharField(label="", error_messages=error_messages, widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password2 = forms.CharField(label="", error_messages=error_messages, widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2"
        ]

    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get("email")

        # if not "dhvsu.edu.ph" in email:
        #     raise forms.ValidationError("Must be a DHVSU account!")
        
        return email

library/forms.py
from django import forms

from . models import *

class DocumentForm(forms.ModelForm):
    
    class Meta:
        model = Document
        fields = [
            "title",
            "school_year",
            "abstract",
            "group",
            "course",
            "file"
        ]
    

administration/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from library.models import *


# Create your views here.
def admin_view_redirect(request):
    return redirect("adminview")

def admin_view(request):
    return render(request, "admin.html", {})

def users(request):
    user = get_user_model()
    _users = user.objects.all()
    context = {
        "users" : _users,
    }

    return render(request, "users.html", context)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from . forms import *

def authentication(request):
    context = {}

    if request.user.is_authenticated:
        return redirect("home")
    
    if request.method == "POST" and request.POST.get("login-button"):
        
        username = request.POST.get("username")
        password = request.POST.get("password")
    
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            print("Logged in!")
            return redirect("home")

        
    form = RegisterForm(request.POST or None)

    if request.method == "POST" and request.POST.get("register-button"):
        if(form.is_valid()):
            form.save()
            form = RegisterForm()
            return redirect("home")

    context['form'] = form

    return render(request, "authentication.html", context)

def logout_view(request):
    logout(request)
    return redirect("authentication:authentication")

base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required(login_url="authentication:authentication")
def home(request):
    return render(request, "home.html")

library/views.py
from django.shortcuts import render, redirect

from . forms import *

def library(request):
    form = DocumentForm()
    context = {}

    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("library")

        print(form.errors)
        return redirect("library")
    

    form.fields['title'].widget.attrs.update({'class': 'title','id': 'title'})
    form.fields['school_year'].widget.attrs.update({'class': 'school_year','id': 'school_year'})
    form.fields['abstract'].widget.attrs.update({'class': 'abstract','id': 'abstract'})
    form.fields['group'].widget.attrs.update({'class': 'group','id': 'group'})
    form.fields['course'].widget.attrs.update({'class': 'course','id': 'course'})
    form.fields['file'].widget.attrs.update({'class': 'file','id': 'file'})

    context["form"] = form.as_p
    return render(request, "library.html", context)

def documents(request):
    documents = Document.objects.all()

    context = {
        "documents" : documents,
    }
    return render(request, "documents.html", context)

def document(request, id):
    document = Document.objects.get(id=id)
    
    context = {
        "document" : document,
    }

    
    return render(request, "document.html", context)

administration/templates/admin.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
<link rel="stylesheet" href="{% static "css/admin_dash.css" %}">
<div class="container">
    <aside>
        <div class="toggle">
            <div class="logo">
                <a href="{% url 'home' %}">
                <img src={% static "img/logo.png" %}>
                </a>
                <h2 style = "color: #600414;">DHVSU<span style="color: #ffbc2c ;">Archives</span></h2>
            </div>
            <div class="close" id="close-btn">
                <span class="material-icons-sharp">
                    close
                </span>
            </div>
        </div>

        <div class="sidebar">
            <a href="">
                <span class="material-icons-sharp">dashboard</span>
                <h3>Dashboard</h3>
            </a>
            <a href="{% url "documents" %}">
                <span class="material-icons-sharp">description</span>
                <h3>Documents</h3>
            </a>
            <a href="{% url "users" %}">
                <span class="material-icons-sharp">group</span>
                <h3>Users</h3>
            </a>
            <a href="#">
                <span class="material-icons-sharp">group</span>
                <h3>Groups</h3>
            </a>
            <a href="#">
                <span class="material-icons-sharp">person_outline</span>
                <h3>Authors</h3>
            </a>
            <a href="#">
                <span class="material-icons-sharp">settings</span>
                <h3>Settings</h3>
            </a>
            <a href="#">
                <span class="material-icons-sharp">
                    logout
                </span>
                <h3>Logout</h3>
            </a>
        </div>
    </aside>
    <!-- End of Sidebar Section -->
</div>


<script>
    const sideMenu = document.querySelector('aside');
    const menuBtn = document.getElementById('menu-btn');
    const closeBtn = document.getElementById('close-btn');

    const darkMode = document.querySelector('.dark-mode');

    menuBtn.addEventListener('click', () => {
        sideMenu.style.display = 'block';
    });

    closeBtn.addEventListener('click', () => {
        sideMenu.style.display = 'none';
    });

    darkMode.addEventListener('click', () => {
        document.body.classList.toggle('dark-mode-variables');
        darkMode.querySelector('span:nth-child(1)').classList.toggle('active');
        darkMode.querySelector('span:nth-child(2)').classList.toggle('active');
    })


    Orders.forEach(order => {
        const tr = document.createElement('tr');
        const trContent = `
            <td>${order.productName}</td>
            <td>${order.productNumber}</td>
            <td>${order.paymentStatus}</td>
            <td class="${order.status === 'Declined' ? 'danger' : order.status === 'Pending' ? 'warning' : 'primary'}">${order.status}</td>
            <td class="primary">Details</td>
        `;
        tr.innerHTML = trContent;
        document.querySelector('table tbody').appendChild(tr);
    });
</script>
{% comment %} Contents of Admin Page:
- Admin Profile
- Website Settings

- Documents
-> Official Documents
--> Theses
--> Dissertations
--> Capstonees

-> On-Hold


- Database
-> Admin List
-> User List
-> Department List
-> ... {% endcomment %}


{% endblock content %}

administration/templates/groups.html
{% extends "base.html" %}

{% block content %}
<h1>Users</h1>

<table>
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Last Login</th>
        <th>Action</th>
    </tr>
    <tr>
        <td>Roi</td>
        <td>roi.zulan@gmail.com</td>
        <td>20202-23134</td>
        <td>
            <a href="">Edit</a>
            <a href="">Delete</a>
        </td>
    </tr>
</table>

<h2>Create User</h2>
<form action="" method="POST">
    {% csrf_token %}
    
    <input type="text" name="" id="">
    <input type="text" name="" id="">
</form>

{% endblock content %}

administration/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1>Admin Profile</h1>

{% endblock content %}

administration/templates/settings.html
{% extends "base.html" %}

{% block content %}
<h1>Admin Settings</h1>

{% endblock content %}

administration/templates/users.html
{% extends "base.html" %}

{% block content %}
<h1>Users</h1>

<table>
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Last Login</th>
        <th>Action</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td>2023-10-24</td>
        <td>
            <a href="">Edit</a>
            <a href="">Delete</a>
        </td>

    </tr>
    {% endfor %}
</table>

<h2>Create User</h2>
<form action="" method="POST">
    {% csrf_token %}
    
    <input type="text" name="" id="">
    <input type="text" name="" id="">
</form>

{% endblock content %}

authentication/templates/authentication.html
{% extends "base.html" %}

{% block content %}

{% load static %}
    <link rel="stylesheet" href="{% static "css/welcome.css" %}">

<div id ="background">
	<div class="container" id="container">
		<div class="form-container sign-up-container">
			<form action="" method="post">
				<h1>REGISTER</h1>
				{% csrf_token %}
				{{ form }}
				<input type="submit" value="Register" name="register-button" id="register-button">
			</form>
		</div>
		<div class="form-container sign-in-container">
			<form action="#" method="POST">
				{% csrf_token %}
				<h1>Login</h1>
				<input type="text" placeholder="Username" name="username" />
				<input type="password" placeholder="Password" name="password" />
				<input type="submit" value="Login" id="login-button" name="login-button">
				<a href="#">Forgot your password?</a>
			</form>
		</div>
		<div class="overlay-container">
			<div class="overlay">
				<div class="overlay-panel overlay-left">
					<a href="{% url 'home' %}">
						<img src="{% static 'img/logo.png' %}" alt="DHVSU Archives Logo" class="logo">
					</a>
					<h1>DHVSU Archives</h1>
					<h4>"Welcome back! Log in to your account to view thesis/capstone"</h4>
					<button class="button" id="signIn">
						LOGIN
						<svg class="icon" viewBox="0 0 24 24" fill="currentColor">
						  <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z" clip-rule="evenodd"></path>
						</svg>
					  </button>
				</div>
				<div class="overlay-panel overlay-right">
					<a href="{% url 'home' %}">
						<img src="{% static 'img/logo.png' %}" alt="DHVSU Archives Logo" class="logo">
					</a>
					<h1>DHVSU Archives</h1>
					<h4>"Preserving Academic Brilliance: Journey Through the Past, Present, and Future of Research with Our Thesis Archive."</h4>
					<button class="button" id="signUp">
						REGISTER
						<svg class="icon" viewBox="0 0 24 24" fill="currentColor">
						  <path fill-rule="evenodd" d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm4.28 10.28a.75.75 0 000-1.06l-3-3a.75.75 0 10-1.06 1.06l1.72 1.72H8.25a.75.75 0 000 1.5h5.69l-1.72 1.72a.75.75 0 101.06 1.06l3-3z" clip-rule="evenodd"></path>
						</svg>
					  </button>
				</div>
			</div>
		</div>
	</div>

</div>

<script>
	const signUpButton = document.getElementById('signUp');
	const signInButton = document.getElementById('signIn');
	const container = document.getElementById('container');

	signUpButton.addEventListener('click', () => {
		container.classList.add("right-panel-active");
	});

	signInButton.addEventListener('click', () => {
		container.classList.remove("right-panel-active");
	});
</script>

<script>
	
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.net.min.js"></script>
<script>
	VANTA.NET({
	el: "#background",
	mouseControls: true,
	touchControls: true,
	gyroControls: false,
	minHeight: 200.00,
	minWidth: 200.00,
	scale: 1.00,
	scaleMobile: 1.00,
	color: 0xffbc2c ,
	backgroundColor: 0xFFFFFF,
	maxDistance: 18.00
	})
</script>

{% endblock content %}

base/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DHVSU Archives | {% block title %}Welcome!{% endblock title %}</title>


</head>
<body>

    {% block content %}
    {% endblock content %}
</body>
</html>

base/templates/footer.html
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "css/footer.css" %}">


<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col">
                <h4>Member</h4>
                <ul>
                <li><a href="#">King Jhusfer Manuel</a></li>
                    <li><a href="#">Alfredo Roi Naluz</a></li>
                    <li><a href="#">John Ford Actub</a></li>
                    <li><a href="#">Adrian Paul Sapnu</a></li>
                 <li><a href="#">Dhen Andrei Tique</a></li>
                 <li><a href="#">Jerome Bondoc Guina</a></li>
                 <li><a href="#">Mc Karl Kennedy Javier</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Computer Science</h4>
                <ul>
                    <li><a href="#">About Us</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Thesis</h4>
                <ul>
                    <li><a href="#">Hatdog</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>
{% endblock content %}

base/templates/header.html
{% block content %}

{% block css %}

{% load static %}
<link rel="stylesheet" href="{% static "css/header.css" %}">
{% endblock css %}



<div class="header-nav-container">

    <header>
        <div class="logo">
            <img src="{% static "img/logoW.png" %}" alt="DHVSU Archives Logo">
            <h1><a href="{% url "home" %}">DHVSU Archives</a></h1>
        </div>
    </header>
    
    <nav>
        <ul>
            <li class="dropdown">
                <a href="{% url "home" %}" class="dropdown-toggle">Home</a>
                <ul class="dropdown-menu">
                    <li><a href="#featured" id="featured-link">Featured Documents</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle">Department</a>
                <ul class="dropdown-menu">
                    <li><a href="#">CCS</a></li>
                    <li><a href="#">CEA</a></li>
                    <li><a href="#">School of Law</a></li>
                    <li><a href="#">Graduate School</a></li>
                    <li><a href="#">CAS</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="{% url "documents" %}" class="dropdown-toggle">Library</a>
                <ul class="dropdown-menu">
                    <li><a href="#">Theses</a></li>
                    <li><a href="#">Dissertations</a></li>
                    <li><a href="#">Capstones</a></li>
                </ul>
            </li>
            <li><a href="#">Profile</a></li>
            {% if user.is_superuser %}
            <li><a href="{% url "library" %}">Submit Document</a></li>
            <li><a href="{% url "adminview" %}">Admin</a></li>
            {% endif %}
        </ul>
    </nav>
    
    <div class="user-info">
        {% if user.is_authenticated %}
            <span id="welcome-user">Welcome <u>{{ user.username }}</u> | </span>
            <a href="{% url 'authentication:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'authentication:authentication' %}">Login/Register</a>
        {% endif %}
    </div>

 </div>

 <script>
    let prevScrollPos = window.pageYOffset;
const header = document.querySelector('.header-nav-container');
const navLinks = document.querySelectorAll('nav li a');
const dropdownMenus = document.querySelectorAll('.dropdown-menu');

window.onscroll = function() {
    const currentScrollPos = window.pageYOffset;

    if (currentScrollPos === 0) {
        // At the top of the page
        header.style.backgroundColor = 'rgba(0, 0, 0, 0.5)';
        header.style.color = '#fff';
        document.querySelector('.logo img').src = "{% static "img/logoW.png" %}";
        document.querySelector('.logo h1 a').style.color = '#fff';
        document.querySelector('.user-info a').style.color = '#fff';
        navLinks.forEach(link => {
            link.style.color = '#fff';
        });
        header.style.borderTop = '10px solid #600414';
        header.classList.remove('header-hidden');
        header.style.height = '105px';
    } else if (prevScrollPos > currentScrollPos) {
        // Scrolling up
        header.style.backgroundColor = 'white';
        header.style.color = '#000';
        document.querySelector('.logo img').src = "{% static "img/logo.png" %}";
        document.querySelector('.logo h1 a').style.color = '#600414';
        document.querySelector('.user-info a').style.color = '#000';
        navLinks.forEach(link => {
            link.style.color = '#000';
        });
        header.style.borderTop = '10px solid #600414';
        header.classList.remove('header-hidden');
        header.style.height = '100px';
    } else {
        // Scrolling down
        header.classList.add('header-hidden');
    }

    dropdownMenus.forEach(dropdownMenu => {
        const isDropdownOpen = dropdownMenu.style.display === 'block';

        if (isDropdownOpen || currentScrollPos === 0) {
            dropdownMenu.style.backgroundColor = 'rgba(0, 0, 0, 0.5)';
        } else {
            dropdownMenu.style.backgroundColor = 'white';
        }
    });

    prevScrollPos = currentScrollPos;
};

</script>


{% endblock content %}

base/templates/home.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static "css/index.css" %}">
{% include "header.html" %}


<section class="welcome">
    <div class="mBG"></div>
    <img src="{% static "img/welcomeT.png" %}" alt="welcome">
</section>


<!-- <section aria-label="slide">
    <div class="carousel" data-carousel>
      <button class="carousel-button prev" data-carousel-button="prev">&#8656;</button>
      <button class="carousel-button next" data-carousel-button="next">&#8658;</button>
      <ul data-slides>
        <li class="slide" data-active>
          <img src="img/welcome.png" alt="welcome">
        </li>
        <li class="slide">
          <img src="img/welcomeW.png" alt="welcomeW">
        </li>
      </ul>
    </div>
</section> -->

<section class ="featured-content" id="featured">

    <div class="featured">
        <h1>Featured Document</h1>
    </div>


    <div class = "sample-content">
        <div class="card hidden">
            <div class="content">
                <p class="heading">Thesis example
                </p><p class="para">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi
                laboriosam at voluptas minus culpa deserunt delectus sapiente
                inventore pariatur
                </p>
                <button class="learn-more">
                <span class="circle" aria-hidden="true">
                <span class="icon arrow"></span>
                </span>
                <span class="button-text">Read More</span>
                </button>
            </div>
        </div>
        <div class="card hidden">
            <div class="content">
                <p class="heading">Thesis example
                </p><p class="para">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi
                laboriosam at voluptas minus culpa deserunt delectus sapiente
                inventore pariatur
                </p>
                </p>
                <button class="learn-more">
                <span class="circle" aria-hidden="true">
                <span class="icon arrow"></span>
                </span>
                <span class="button-text">Read More</span>
                </button>
            </div>
        </div>
        <div class="card hidden">
            <div class="content">
                <p class="heading">Thesis example
                </p><p class="para">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi
                laboriosam at voluptas minus culpa deserunt delectus sapiente
                inventore pariatur
                </p>
                </p>
                <button class="learn-more">
                <span class="circle" aria-hidden="true">
                <span class="icon arrow"></span>
                </span>
                <span class="button-text">Read More</span>
                </button>
            </div>
        </div>
        <div class="card hidden">
            <div class="content">
                <p class="heading">Thesis example
                </p><p class="para">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi
                laboriosam at voluptas minus culpa deserunt delectus sapiente
                inventore pariatur
                </p>
                </p>
                <button class="learn-more">
                <span class="circle" aria-hidden="true">
                <span class="icon arrow"></span>
                </span>
                <span class="button-text">Read More</span>
                </button>
            </div>
        </div>
    </div>
    
</section>


{% include "footer.html" %}

<script>
    const buttons = document.querySelectorAll("[data-carousel-button]")

    buttons.forEach(button => {
    button.addEventListener("click", () => {
        const offset = button.dataset.carouselButton === "next" ? 1 : -1
        const slides = button
        .closest("[data-carousel]")
        .querySelector("[data-slides]")

        const activeSlide = slides.querySelector("[data-active]")
        let newIndex = [...slides.children].indexOf(activeSlide) + offset
        if (newIndex < 0) newIndex = slides.children.length - 1
        if (newIndex >= slides.children.length) newIndex = 0

        slides.children[newIndex].dataset.active = true
        delete activeSlide.dataset.active
    })
    })
</script>

<script>
    let lastScrollTop = 0; // Variable to store the last scroll position

    window.addEventListener("scroll", () => {
        const cards = document.querySelectorAll(".card");
        const currentScrollTop = window.pageYOffset || document.documentElement.scrollTop;

        // Check the scroll direction (down or up)
        const scrollDirection = currentScrollTop > lastScrollTop ? "down" : "up";

        cards.forEach((card) => {
            if (isElementInViewport(card) && card.classList.contains("hidden")) {
                card.classList.remove("hidden");
                card.classList.add("animate"); // Add the "animate" class
            } else if (!isElementInViewport(card) && scrollDirection === "up") {
                card.classList.add("hidden");
                card.classList.remove("animate"); // Remove the "animate" class
            }
        });

        // Update the last scroll position
        lastScrollTop = currentScrollTop;
    });

    function isElementInViewport(el) {
        const rect = el.getBoundingClientRect();
        return (
            rect.top >= 0 &&
            rect.left >= 0 &&
            rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
            rect.right <= (window.innerWidth || document.documentElement.clientWidth)
        );
    }
</script>



<script>
    // Function to smoothly scroll to the target element
    function scrollToTarget(element) {
        window.scrollTo({
            behavior: 'smooth',
            top: element.offsetTop - 50, // Adjust the offset as needed
        });
    }

    // Add an event listener to the "Featured" link
    const featuredLink = document.getElementById('featured-link');
    const featuredSection = document.getElementById('featured');


    if (featuredLink && featuredSection) {
        featuredLink.addEventListener('click', (event) => {
            event.preventDefault(); // Prevent the default anchor link behavior
            scrollToTarget(featuredSection);
        });
    }
</script>
{% endblock content %}

library/templates/document.html
{% extends "base.html" %}

{% block content %}
<h1>Document - {{ document.title }}</h1>

{% endblock content %}

library/templates/library.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% include "header.html" %}
<link rel="stylesheet" href="{% static "css/library.css" %}">

<section class="container">
    <div class="submit-doc">
        <h1>Submit Document</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
        
            <input type="submit" value="Submit">
        </form>
    </div>
</section>



{% endblock content %}

library/templates/official.html
{% extends "base.html" %}

{% block content %}
<h1>Documents</h1>
<h3>Official Documents</h3>

{% endblock content %}

library/templates/onhold.html
{% extends "base.html" %}

{% block content %}
<h1>Documents</h1>
<h3>Official Documents</h3>

{% endblock content %}